### ISSUE TITLE
external legends for strata

### ISSUE THREAD

**Issue by Jgruetzke** [erblast/easyalluvial#17]
Hey,

easyalluvial is a great tool. I was wondering if it is planned to create an option for having the legend for the strata outside of the plot. My problem is that my strata labels are long and partly cover the plot. Or is there already a solution for this that I have missed? 

Many thanks!

**Comment by erblast** [comment]
Hello thanks for your suggestions,
strata legends are currently not supported in `ggalluvial` so there is no easy solution. What you can do is introducing linebreaks in your labels using `\n` and adjust the width of the strata using the stratum_width parameter make it fit. 
If you want a pixel-perfect plot maybe switch to using `ggalluvial` directly and consider one of these [methods](https://corybrunson.github.io/ggalluvial/articles/labels.html).
Another solution would be to create a dummy plot that would produce a legend that looks like the one you want and then extract it using `cowplot::get_legend()`.  You can then switch of the labels of the alluvial plot using the stratum_labels parameter.
It is a little bit hard to generalise this for all plots that one might want to create. Would you mind sharing your plot and how the legend is supposed to look like?

**Comment by Jgruetzke** [comment]
Hi,

thank you for your great suggestions! In the end I used ggalluvial. Here is a mixed plot of easyalluvial with the legend of ggalluvial.

Thank you!
![alluvial_plot_strain_prediction_subsampling_easyalluvial](https://user-images.githubusercontent.com/28339457/77059127-bfcca880-69d6-11ea-876a-488248215c18.png)

**Comment by erblast** [comment]
thanks for sharing, could you also post the ggalluvial code that you used to get the legend? I actually thought that ggalluvial did not give you the strata legends but maybe I got it wrong.

**Comment by Jgruetzke** [comment]
Hi,
I got it from the vignette of ggalluvial: https://cran.r-project.org/web/packages/ggalluvial/vignettes/ggalluvial.html

The problem with ggalluvial is that it also adds the tools to the legend. 
This code was only used to get the legend (without geom_flow and geom_alluvium):
`ggplot(strain, aes(x = reads, stratum = prediction)) +
  geom_stratum(aes(fill=prediction))+
  scale_fill_manual(values=c( 'orange', 'green3', 'blue', 'yellow', 'lightgreen', 'tomato')) +
  theme(legend.position = "bottom")`

**Comment by erblast** [comment]
ah thank you.
