### ISSUE TITLE
jamovi integration

### ISSUE THREAD

**Issue by sbalci** [erblast/easyalluvial#19]
Dear @erblast 
Thank you for the package.
I am collecting the codes that I use as jamovi modules. (https://github.com/sbalci/ClinicoPathJamoviModule)

I have prepared a function using easyalluvial package. See gif below:

![jamovi-ClinicoPath-easyalluvial](https://user-images.githubusercontent.com/7208830/82695236-62223a00-9c6d-11ea-92e5-8c073e9cc0a8.gif)

I think it will be a good method to visualize both data and models. I will try to add model response codes as well.

Please let me know your comments.

**Comment by erblast** [comment]
this looks really cool. Would love to check it out, however I do not manage to load your extension into jamovi. I use sideload as described but then when listing the installed versions it says `installed version is incompatible`. I use `0.0.2` of your module and jamovi `1.1.9.0` on macOS `10.14.6`

**Comment by sbalci** [comment]
Thank you.
Please get the latest version `jamovi 1.2.19` from https://www.jamovi.org/download.html
Please use `jmo` file here for sideload: https://github.com/sbalci/ClinicoPathJamoviModule/releases/tag/v0.0.2.0006

**Comment by erblast** [comment]
great, now it works, let me know once easyalluvial makes it into your next stable version and I will start linking to it.

**Comment by sbalci** [comment]
Sure, I will let you know. Thank you for your support :)

**Comment by erblast** [comment]
thanks will check it out, and then link to it from the easyalluvial page. Give me some time though

**Comment by erblast** [comment]
8d474a24e74d46af81dd5047e1be1fa7cf975e8e
