### ISSUE TITLE
reverse dependency error from ggalluvial 0.12.5

### ISSUE THREAD

**Issue by corybrunson** [erblast/easyalluvial#29]
Hello,

I'm preparing to release {ggalluvial} version 0.12.5, a patch that corrects a previous patch to fix a bug resulting from the new {dplyr} version 1.1.0. I got the email below from the CRAN team suggesting an issue with the reverse dependency {easyalluvial}.

I tried installing {easyalluvial} on multiple machines with different version of {ggalluvial} and encountered no such error myself, though i only have Macs at my disposal whereas the issue seems to occur on Windows, and anyway the error message provides no details. So i wonder if you have any insight into it. {ggalluvial} 0.12.4 is currently on CRAN, while 0.12.5 is the [current development version](https://github.com/corybrunson/ggalluvial).

No worries if not—i've asked the maintainers for guidance on next steps. Thanks in advance!

Cory

```
Dear maintainer,
 
package ggalluvial_0.12.5.tar.gz has been auto-processed. The auto-check found problems when checking the first order strong reverse dependencies.
Please reply-all and explain: Is this expected or do you need to fix anything in your package? If expected, have all maintainers of affected packages been informed well in advance? Are there false positives in our results?
 
*** Changes to worse in reverse dependencies ***
Debian: [<https://win-builder.r-project.org/incoming_pretest/ggalluvial_0.12.5_20230213_172426/reverseDependencies/summary.txt>](https://win-builder.r-project.org/incoming_pretest/ggalluvial_0.12.5_20230213_172426/reverseDependencies/summary.txt)
 
Log dir: [<https://win-builder.r-project.org/incoming_pretest/ggalluvial_0.12.5_20230213_172426/>](https://win-builder.r-project.org/incoming_pretest/ggalluvial_0.12.5_20230213_172426/)
The files will be removed after roughly 7 days.
 
Pretests:
Windows: [<https://win-builder.r-project.org/incoming_pretest/ggalluvial_0.12.5_20230213_172426/Windows/00check.log>](https://win-builder.r-project.org/incoming_pretest/ggalluvial_0.12.5_20230213_172426/Windows/00check.log)
Debian: [<https://win-builder.r-project.org/incoming_pretest/ggalluvial_0.12.5_20230213_172426/Debian/00check.log>](https://win-builder.r-project.org/incoming_pretest/ggalluvial_0.12.5_20230213_172426/Debian/00check.log)
 
Last published version on CRAN:
 
CRAN Web: [<https://cran.r-project.org/package=ggalluvial>](https://cran.r-project.org/package=ggalluvial)
 
Best regards,
CRAN teams' auto-check service


Package check result: OK

Changes to worse in reverse depends:

Package: easyalluvial
Check: whether package can be installed
New result: ERROR
  Installation failed.
```

**Comment by erblast** [comment]
Hi Cory,

thanks for letting me know. I am also currently on Mac and also cannot recreate the error.  Please confirm to CRAN that you have informed me and please go ahead with your submission. I will try on my old windows machine later and add a fix if needed.

Cheers

Björn

**Comment by erblast** [comment]
I just saw that your new version is on CRAN already. I have not received any news from CRAN since then so I assume everything is fine.

**Comment by corybrunson** [comment]
Yes, it seems to be—i did just what you suggested, and the CRAN team went ahead. Thank you!
