### ISSUE TITLE
Current version not on CRAN (9/11/2023)

### ISSUE THREAD

**Issue by greenwood-stat** [erblast/easyalluvial#30]
It looks like the current version was removed from CRAN. I really appreciate this package and along with visualizing complex data sets, I also use it to teach about design matrices in linear models in my classes, so keeping it easy to get for student use would be great. Thanks!

**Comment by gernophil** [comment]
+1 for this. I really would love to see this back on CRAN.

**Comment by erblast** [comment]
sorry about this, I missed all of the notifications somehow, will fix this ASAP

**Comment by gernophil** [comment]
Could you maybe consider my PR, if you're about to update stuff anyway :)?

**Comment by erblast** [comment]
oh great did not see that either, need to check in here more often. Looks good so far, thanks for submitting
